name: Generate Snake

on:
  schedule: # execute after every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AthanasyFotis
          gif_out_path: dist/AthanasyFotis.gif
          svg_out_path: dist/AthanasyFotis.svg


      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: athanasy-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
